# Generated by Django 4.1 on 2022-11-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entry_creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('entry_updated_datetime', models.DateTimeField()),
                ('title', models.TextField(max_length=120)),
                ('director_name', models.TextField(max_length=80)),
                ('premier_date', models.DateField()),
                ('movie_projection_time_slot', models.JSONField(blank=True, null=True)),
                ('ticket_price', models.FloatField()),
                ('sinopsis', models.TextField(max_length=300)),
                ('img_path', models.TextField(max_length=300)),
                ('pegi', models.IntegerField()),
                ('genre', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
